version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mnbcontrol
    main: ./cmd/mnbcontrol
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
